/* =========================================================================
   Données de la galerie Pascal Sun
   ➜ Pour publier une nouvelle œuvre : ajouter un objet dans ARTWORKS
     et déposer la photo dans /img (remplacer les visuels SVG d'attente
     par les photos réelles des toiles, même nom de fichier ou nouveau).
   ➜ prixEUR : prix de base en euros (conversion auto XPF / USD).
   ➜ vendu : true pour afficher « Œuvre vendue ».
   ========================================================================= */

var ARTWORKS = [
  {
    "id": "le-retour-de-peche",
    "titre": "Le retour de pêche",
    "collection": "ocean",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2400,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": true,
    "image": "img/oeuvres/le-retour-de-peche-960.webp",
    "images": {
      "small": "img/oeuvres/le-retour-de-peche-480.webp",
      "medium": "img/oeuvres/le-retour-de-peche-960.webp",
      "large": "img/oeuvres/le-retour-de-peche-1600.webp"
    },
    "desc_fr": "Le regard tourné vers le large, la prise du jour à bout de bras. Quatre poissons de corail, seule couleur d'un matin tranquille.",
    "desc_en": "Gazing out to sea, the day's catch in hand. Four coral-coloured fish, the only colour of a quiet morning."
  },
  {
    "id": "la-pecheuse-au-chapeau",
    "titre": "La pêcheuse au chapeau",
    "collection": "vahine",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2400,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": true,
    "image": "img/oeuvres/la-pecheuse-au-chapeau-960.webp",
    "images": {
      "small": "img/oeuvres/la-pecheuse-au-chapeau-480.webp",
      "medium": "img/oeuvres/la-pecheuse-au-chapeau-960.webp",
      "large": "img/oeuvres/la-pecheuse-au-chapeau-1600.webp"
    },
    "desc_fr": "Un sourire sous le grand chapeau, la tresse sur l'épaule et la pêche du jour qui s'anime d'orange. La joie simple du retour.",
    "desc_en": "A smile beneath the wide hat, a braid over the shoulder, the day's catch glowing orange. The simple joy of coming home."
  },
  {
    "id": "le-pecheur-au-harpon",
    "titre": "Le pêcheur au harpon",
    "collection": "ocean",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2400,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/le-pecheur-au-harpon-960.webp",
    "images": {
      "small": "img/oeuvres/le-pecheur-au-harpon-480.webp",
      "medium": "img/oeuvres/le-pecheur-au-harpon-960.webp",
      "large": "img/oeuvres/le-pecheur-au-harpon-1600.webp"
    },
    "desc_fr": "De dos, face au motu, la nasse à la main et les poissons accrochés à la ceinture. La patience de celui qui connaît le lagon.",
    "desc_en": "Seen from behind, facing the motu, fish trap in hand and the catch hanging from his belt. The patience of a man who knows the lagoon."
  },
  {
    "id": "le-filet-face-a-moorea",
    "titre": "Le filet, face à Moorea",
    "collection": "ocean",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "146 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2900,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/le-filet-face-a-moorea-960.webp",
    "images": {
      "small": "img/oeuvres/le-filet-face-a-moorea-480.webp",
      "medium": "img/oeuvres/le-filet-face-a-moorea-960.webp",
      "large": "img/oeuvres/le-filet-face-a-moorea-1600.webp"
    },
    "desc_fr": "Assis sur le balancier de sa pirogue, il relève le filet où frétillent quelques taches de corail. Moorea veille, esquissée dans la brume.",
    "desc_en": "Sitting on his canoe's outrigger, he pulls in a net flecked with coral. Moorea watches over him, sketched in the haze."
  },
  {
    "id": "la-vahine-a-la-couronne",
    "titre": "La vahine à la couronne",
    "collection": "vahine",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "100 × 100 cm",
    "orientation": "portrait",
    "prixEUR": 2200,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": true,
    "image": "img/oeuvres/la-vahine-a-la-couronne-960.webp",
    "images": {
      "small": "img/oeuvres/la-vahine-a-la-couronne-480.webp",
      "medium": "img/oeuvres/la-vahine-a-la-couronne-960.webp",
      "large": "img/oeuvres/la-vahine-a-la-couronne-1600.webp"
    },
    "desc_fr": "Accoudée, sereine, sous une couronne de fleurs tressées. Une pointe d'orange hibiscus, et tout le calme du fenua dans un regard.",
    "desc_en": "Leaning on her elbow, serene beneath a crown of woven flowers. A hint of hibiscus orange, and all the calm of the fenua in one gaze."
  },
  {
    "id": "le-tressage",
    "titre": "Le tressage",
    "collection": "vahine",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 89 cm",
    "orientation": "portrait",
    "prixEUR": 2600,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/le-tressage-960.webp",
    "images": {
      "small": "img/oeuvres/le-tressage-480.webp",
      "medium": "img/oeuvres/le-tressage-960.webp",
      "large": "img/oeuvres/le-tressage-1600.webp"
    },
    "desc_fr": "Une mère tresse les cheveux de sa fille, paréos orange et turquoise. Le geste transmis, de génération en génération.",
    "desc_en": "A mother braids her daughter's hair, pareos of orange and turquoise. A gesture handed down, generation after generation."
  },
  {
    "id": "l-homme-au-coq",
    "titre": "L'homme au coq",
    "collection": "village",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "116 × 89 cm",
    "orientation": "portrait",
    "prixEUR": 2200,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/l-homme-au-coq-960.webp",
    "images": {
      "small": "img/oeuvres/l-homme-au-coq-480.webp",
      "medium": "img/oeuvres/l-homme-au-coq-960.webp",
      "large": "img/oeuvres/l-homme-au-coq-1600.webp"
    },
    "desc_fr": "Assis au frais, le coq sur le genou, le sourire tranquille. Une scène de tous les jours, quelque part entre Vaitape et l'éternité.",
    "desc_en": "Sitting in the shade, rooster on his knee, an easy smile. An everyday scene, somewhere between Vaitape and eternity."
  },
  {
    "id": "la-recolte-des-cocos",
    "titre": "La récolte des cocos",
    "collection": "autrefois",
    "annee": 2024,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2600,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/la-recolte-des-cocos-960.webp",
    "images": {
      "small": "img/oeuvres/la-recolte-des-cocos-480.webp",
      "medium": "img/oeuvres/la-recolte-des-cocos-960.webp",
      "large": "img/oeuvres/la-recolte-des-cocos-1600.webp"
    },
    "desc_fr": "Le village entier s'y met : on cueille, on trie, on charge la charrette. Le coprah d'autrefois, raconté au fusain.",
    "desc_en": "The whole village pitches in: picking, sorting, loading the cart. The copra days of old, told in charcoal."
  },
  {
    "id": "devant-le-fare",
    "titre": "Devant le faré",
    "collection": "village",
    "annee": 2024,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2600,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/devant-le-fare-960.webp",
    "images": {
      "small": "img/oeuvres/devant-le-fare-480.webp",
      "medium": "img/oeuvres/devant-le-fare-960.webp",
      "large": "img/oeuvres/devant-le-fare-1600.webp"
    },
    "desc_fr": "La vieille voiture, la tablée sous le toit de pandanus, la vahine qui passe. Un dimanche comme on n'en fait plus — et pourtant.",
    "desc_en": "The old car, the table beneath the pandanus roof, a vahine passing by. A Sunday like they no longer make — and yet."
  },
  {
    "id": "le-camion-de-coprah",
    "titre": "Le camion de coprah",
    "collection": "autrefois",
    "annee": 2024,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "130 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2800,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": true,
    "image": "img/oeuvres/le-camion-de-coprah-960.webp",
    "images": {
      "small": "img/oeuvres/le-camion-de-coprah-480.webp",
      "medium": "img/oeuvres/le-camion-de-coprah-960.webp",
      "large": "img/oeuvres/le-camion-de-coprah-1600.webp"
    },
    "desc_fr": "Le vieux camion rouille sous sa montagne de cocos, le chauffeur au chapeau salue. La couleur, ici, c'est la tôle chauffée de soleil.",
    "desc_en": "The old truck rusts beneath its mountain of coconuts, the hatted driver waves. Here the colour is sheet metal warmed by the sun."
  },
  {
    "id": "la-vahine-au-pareo-bleu",
    "titre": "La vahine au paréo bleu",
    "collection": "vahine",
    "annee": 2025,
    "technique_fr": "Fusain et acrylique sur toile",
    "technique_en": "Charcoal and acrylic on canvas",
    "dimensions": "146 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2900,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": true,
    "image": "img/oeuvres/la-vahine-au-pareo-bleu-960.webp",
    "images": {
      "small": "img/oeuvres/la-vahine-au-pareo-bleu-480.webp",
      "medium": "img/oeuvres/la-vahine-au-pareo-bleu-960.webp",
      "large": "img/oeuvres/la-vahine-au-pareo-bleu-1600.webp"
    },
    "desc_fr": "Elle traverse le marché, oranges dans une main, poissons dans l'autre. Le paréo bleu lagon fait chanter tout le reste, laissé en esquisse.",
    "desc_en": "She crosses the market, oranges in one hand, fish in the other. The lagoon-blue pareo makes everything else sing, left as a sketch."
  },
  {
    "id": "les-fares-du-lagon",
    "titre": "Les farés du lagon",
    "collection": "ocean",
    "annee": 2024,
    "technique_fr": "Technique mixte sur toile",
    "technique_en": "Mixed media on canvas",
    "dimensions": "97 × 130 cm",
    "orientation": "landscape",
    "prixEUR": 3200,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/les-fares-du-lagon-960.webp",
    "images": {
      "small": "img/oeuvres/les-fares-du-lagon-480.webp",
      "medium": "img/oeuvres/les-fares-du-lagon-960.webp",
      "large": "img/oeuvres/les-fares-du-lagon-1600.webp"
    },
    "desc_fr": "Au-dessus, les farés sur pilotis et une barque jaune. Au-dessous, le banc de poissons dans le bleu. Deux mondes, une seule respiration.",
    "desc_en": "Above, stilt houses and a small yellow boat. Below, a school of fish in the blue. Two worlds, one single breath."
  },
  {
    "id": "le-sechoir-a-poissons",
    "titre": "Le séchoir à poissons",
    "collection": "village",
    "annee": 2024,
    "technique_fr": "Technique mixte sur toile",
    "technique_en": "Mixed media on canvas",
    "dimensions": "146 × 97 cm",
    "orientation": "portrait",
    "prixEUR": 2900,
    "vendu": false,
    "statut": "disponible",
    "nouveaute": false,
    "image": "img/oeuvres/le-sechoir-a-poissons-960.webp",
    "images": {
      "small": "img/oeuvres/le-sechoir-a-poissons-480.webp",
      "medium": "img/oeuvres/le-sechoir-a-poissons-960.webp",
      "large": "img/oeuvres/le-sechoir-a-poissons-1600.webp"
    },
    "desc_fr": "Le ciel charge, le vent se lève, les poissons sèchent encore. Le paréo bleu claque comme une voile — l'orage attendra.",
    "desc_en": "The sky darkens, the wind picks up, the fish are still drying. The blue pareo snaps like a sail — the storm can wait."
  }
];

/* ----------------------------------------------------- boutique / stock -- */
/* Chaque œuvre est déclinée en produits : original unique, tirage d'art en
   édition limitée, affiche. Statut d'une œuvre : disponible | reserve | vendu
   (l'original passe automatiquement en « réservée » à la commande).
   Tout est modifiable dans l'espace admin. */

function defaultProduits(a) {
  return [
    { key: "original", actif: true, prixEUR: a.prixEUR, stock: 1, certificat: true },
    { key: "tirage", actif: true, prixEUR: 190, stock: 30, edition: 30, certificat: true },
    { key: "affiche", actif: true, prixEUR: 45, stock: 100, certificat: false }
  ];
}

function normalizeArtworks(list) {
  (list || []).forEach((a) => {
    if (!a.statut) a.statut = a.vendu ? "vendu" : "disponible";
    a.vendu = a.statut === "vendu"; // compat badges existants
    if (!Array.isArray(a.produits) || !a.produits.length) a.produits = defaultProduits(a);
  });
  return list;
}

/* --------------------------------------------------------- vernissages -- */
/* Feuille de route des expositions — modifiable dans l'espace admin.
   date au format AAAA-MM-JJ ; les dates futures s'affichent en « À venir ». */

var EVENTS = [
  {
    id: "vernissage-lagon",
    titre: "Vernissage — Collection Lagon",
    lieu: "Galerie d'art, front de mer",
    ville: "Papeete, Tahiti",
    date: "2026-09-18",
    heure: "18h00",
    desc_fr: "Présentation des nouvelles toiles de la collection Océan & pirogues, en présence de l'artiste. Cocktail au coucher du soleil.",
    desc_en: "Unveiling of the new Ocean & canoes collection, in the artist's presence. Sunset cocktail."
  },
  {
    id: "expo-fenua",
    titre: "Exposition collective — Artistes du Fenua",
    lieu: "Salle d'exposition municipale",
    ville: "Punaauia, Tahiti",
    date: "2026-11-06",
    heure: "17h30",
    desc_fr: "Pascal Sun expose aux côtés des peintres et sculpteurs du fenua. Trois toiles inédites.",
    desc_en: "Pascal Sun exhibits alongside painters and sculptors of the fenua. Three new canvases."
  },
  {
    id: "marche-artisans-moorea",
    titre: "Rencontre au marché des artisans",
    lieu: "Marché artisanal",
    ville: "Moorea",
    date: "2026-05-30",
    heure: "09h00",
    desc_fr: "Démonstration de peinture en plein air et rencontres autour des scènes de vie polynésiennes.",
    desc_en: "Open-air painting demonstration and conversations around Polynesian scenes of life."
  }
];

/* ------------------------------------------------------------ devises -- */

const CURRENCIES = {
  EUR: { symbol: "€",   rate: 1,      locale: "fr-FR", position: "after"  },
  USD: { symbol: "$",   rate: 1.09,   locale: "en-US", position: "before" },
  XPF: { symbol: "F",   rate: 119.33, locale: "fr-FR", position: "after"  }
};

/* --------------------------------------------------------- collections -- */

const COLLECTIONS = {
  ocean:     { fr: "Océan & pirogues",   en: "Ocean & canoes" },
  vahine:    { fr: "Vahine",             en: "Vahine" },
  village:   { fr: "Vie de village",     en: "Village life" },
  autrefois: { fr: "Scènes d'autrefois", en: "Scenes of yesteryear" }
};

/* ---------------------------------------------------------------- i18n -- */

var I18N = {
  fr: {
    nav_home: "Accueil",
    nav_gallery: "Galerie",
    nav_artist: "L'artiste",
    nav_contact: "Contact",
    nav_cart: "Panier",
    hero_eyebrow: "Galerie d'art — Tahiti, Polynésie française",
    hero_title: "Peindre le <em>silence</em> de la Polynésie",
    hero_lede: "Scènes de vie polynésiennes en noir et blanc, où une seule touche de couleur guide le regard vers l'essentiel. Œuvres originales, expédiées dans le monde entier.",
    hero_cta: "Découvrir la galerie",
    hero_cta2: "Rencontrer l'artiste",
    featured_eyebrow: "Sélection",
    featured_title: "Œuvres récentes",
    see_all: "Toute la galerie",
    quote: "« Je ne peins pas pour remplir une toile. Je peins pour laisser <span class='hl'>respirer une émotion</span>. »",
    quote_cite: "Pascal Sun",
    promise_eyebrow: "La promesse",
    promise_title: "Une fenêtre ouverte sur un monde apaisé",
    promise_lede: "Chaque tableau est une œuvre originale, unique, signée. Elle est pensée pour apporter de la sérénité, du sourire et du bien-être — chez vous, où que vous soyez dans le monde.",
    value1_t: "Originaux signés",
    value1_p: "Chaque œuvre est une pièce unique, signée de la main de Pascal Sun et accompagnée de son certificat d'authenticité.",
    value2_t: "Livraison mondiale",
    value2_p: "Emballage d'art professionnel et expédition assurée depuis Tahiti vers le monde entier, suivi de bout en bout.",
    value3_t: "Un lien direct",
    value3_p: "Vous achetez directement auprès de l'artiste, sans intermédiaire. Chaque acquisition commence par une conversation.",
    gallery_eyebrow: "Catalogue",
    gallery_title: "La galerie",
    gallery_lede: "Œuvres originales disponibles à l'acquisition. Cliquez sur une toile pour la découvrir en grand, lire son histoire et l'acquérir.",
    filter_all: "Toutes",
    artist_eyebrow: "L'univers",
    artist_title: "L'art de Pascal Sun est une invitation à ralentir",
    atelier_video_t: "L'atelier en mouvement",
    atelier_video_p: "Quelques minutes dans l'atelier de Pascal, à Tahiti : le geste, le silence, la toile qui prend vie.",
    nav_expos: "Vernissages",
    expos_eyebrow: "Feuille de route",
    expos_title: "Vernissages & expositions",
    expos_lede: "Rencontrer les toiles en vrai, échanger avec Pascal, partager un moment autour de l'art du fenua : voici les prochains rendez-vous de la galerie.",
    expos_upcoming: "À venir",
    expos_past: "Déjà passés",
    expos_rsvp: "Je serai là",
    expos_rsvp_subject: "Présence au vernissage",
    expos_empty: "Les prochaines dates seront annoncées ici très bientôt.",
    statut_disponible: "Disponible",
    statut_reserve: "Réservée",
    statut_vendu: "Œuvre vendue",
    choose_format: "Choisir un format",
    prod_original: "Œuvre originale — pièce unique",
    prod_tirage: "Tirage d'art — édition limitée",
    prod_affiche: "Affiche",
    edition_of: "édition de",
    stock_left: "encore disponibles",
    last_one: "dernier exemplaire",
    sold_out: "Épuisé",
    cert_included: "Certificat d'authenticité inclus",
    qty: "Quantité",
    delivery_mode: "Réception",
    delivery_ship: "Livraison (monde entier, assurée)",
    delivery_pickup: "Retrait à Tahiti (atelier / vernissage)",
    payment_method: "Paiement sécurisé",
    pay_card: "Carte bancaire",
    pay_transfer: "Virement bancaire",
    pay_paypal: "PayPal",
    order_success: "Merci ! Votre commande est enregistrée.",
    merci_title: "Māuruuru !",
    merci_lede: "Votre commande est bien enregistrée. Pascal vous écrit personnellement sous 48 h pour confirmer le paiement et organiser la réception de votre œuvre.",
    merci_back: "Revenir à la galerie",
    news_t: "La lettre de l'atelier",
    news_p: "Nouvelles créations, vernissages, collections : recevez les annonces de Pascal, quelques fois par an seulement.",
    news_ph: "Votre email",
    news_btn: "Je m'inscris",
    news_ok: "Bienvenue dans la lettre de l'atelier !",
    news_err: "Adresse invalide ou déjà inscrite.",
    sold: "Œuvre vendue",
    new: "Nouveauté",
    available: "Disponible",
    add_to_cart: "Acquérir cette œuvre",
    in_cart: "Dans votre panier",
    view_work: "Voir l'œuvre",
    spec_year: "Année",
    spec_technique: "Technique",
    spec_dimensions: "Dimensions",
    spec_collection: "Collection",
    spec_availability: "Disponibilité",
    assur1: "Œuvre originale unique, signée, avec certificat d'authenticité.",
    assur2: "Livraison assurée dans le monde entier, emballage d'art professionnel.",
    assur3: "Paiement sécurisé ou virement bancaire — Pascal vous confirme chaque étape personnellement.",
    related_title: "Vous aimerez aussi",
    back_gallery: "← Retour à la galerie",
    cart_title: "Votre panier",
    cart_lede: "Chaque œuvre étant unique, elle est réservée pour vous dès votre demande d'acquisition.",
    cart_empty_t: "Votre panier est vide",
    cart_empty_p: "Les toiles de Pascal n'attendent que votre regard.",
    order_title: "Demande d'acquisition",
    order_sub: "Sous-total",
    order_ship: "Livraison",
    order_ship_val: "Devis personnalisé",
    order_total: "Total œuvres",
    f_name: "Nom complet",
    f_email: "Email",
    f_country: "Pays de livraison",
    f_message: "Message (optionnel)",
    f_message_ph: "Un mot pour Pascal, une question sur l'œuvre…",
    order_btn: "Envoyer ma demande",
    order_note: "En envoyant votre demande, votre messagerie s'ouvre avec le récapitulatif prêt à partir. Pascal vous répond personnellement sous 48 h avec les modalités de paiement sécurisé et de livraison.",
    remove: "Retirer",
    contact_eyebrow: "Contact",
    contact_title: "Écrire à Pascal",
    contact_lede: "Une question sur une œuvre, une commande spéciale, un projet d'exposition ? Pascal lit et répond personnellement à chaque message, depuis son atelier à Tahiti.",
    f_subject: "Sujet",
    f_subject_ph: "Question sur une œuvre, commande personnalisée…",
    contact_btn: "Envoyer le message",
    studio_t: "L'atelier",
    studio_p: "Tahiti — Polynésie française",
    followup_t: "Réponse",
    followup_p: "Personnelle, sous 48 h",
    ship_t: "Expéditions",
    ship_p: "Monde entier, assurées",
    footer_tag: "Galerie en ligne de l'artiste peintre Pascal Sun. Scènes de vie polynésiennes — noir, blanc, et une touche d'émotion.",
    footer_nav: "Navigation",
    footer_info: "Informations",
    footer_ship: "Livraison mondiale assurée",
    footer_cert: "Certificat d'authenticité",
    footer_secure: "Paiement sécurisé",
    footer_rights: "© 2026 Pascal Sun — Tous droits réservés.",
    footer_made: "Tahiti, Polynésie française",
    toast_added: "ajoutée à votre panier",
    toast_removed: "retirée du panier",
    order_mail_subject: "Demande d'acquisition — Galerie Pascal Sun",
    works_count: "œuvres",
    work_count: "œuvre"
  },
  en: {
    nav_home: "Home",
    nav_gallery: "Gallery",
    nav_artist: "The artist",
    nav_contact: "Contact",
    nav_cart: "Cart",
    hero_eyebrow: "Art gallery — Tahiti, French Polynesia",
    hero_title: "Painting the <em>silence</em> of Polynesia",
    hero_lede: "Polynesian scenes of life in black and white, where a single touch of colour draws the eye to what matters. Original works, shipped worldwide.",
    hero_cta: "Explore the gallery",
    hero_cta2: "Meet the artist",
    featured_eyebrow: "Selection",
    featured_title: "Recent works",
    see_all: "Full gallery",
    quote: "“I don't paint to fill a canvas. I paint to let an <span class='hl'>emotion breathe</span>.”",
    quote_cite: "Pascal Sun",
    promise_eyebrow: "The promise",
    promise_title: "A window onto a world at peace",
    promise_lede: "Every painting is an original, one-of-a-kind, signed work. Each is meant to bring serenity, smiles and well-being — to your home, wherever you are in the world.",
    value1_t: "Signed originals",
    value1_p: "Each work is a unique piece, signed by Pascal Sun's hand and accompanied by its certificate of authenticity.",
    value2_t: "Worldwide shipping",
    value2_p: "Professional art packaging and insured shipping from Tahiti to anywhere in the world, tracked door to door.",
    value3_t: "A direct bond",
    value3_p: "You buy directly from the artist, with no intermediary. Every acquisition begins with a conversation.",
    gallery_eyebrow: "Catalogue",
    gallery_title: "The gallery",
    gallery_lede: "Original works available for acquisition. Click a canvas to see it up close, read its story and make it yours.",
    filter_all: "All",
    artist_eyebrow: "The universe",
    artist_title: "Pascal Sun's art is an invitation to slow down",
    atelier_video_t: "The studio in motion",
    atelier_video_p: "A few minutes inside Pascal's studio in Tahiti: the gesture, the silence, the canvas coming to life.",
    nav_expos: "Exhibitions",
    expos_eyebrow: "Roadmap",
    expos_title: "Openings & exhibitions",
    expos_lede: "Meet the canvases in person, talk with Pascal, share a moment around the art of the fenua: here are the gallery's upcoming events.",
    expos_upcoming: "Upcoming",
    expos_past: "Past events",
    expos_rsvp: "I'll be there",
    expos_rsvp_subject: "Attending the opening",
    expos_empty: "Upcoming dates will be announced here very soon.",
    statut_disponible: "Available",
    statut_reserve: "Reserved",
    statut_vendu: "Sold",
    choose_format: "Choose a format",
    prod_original: "Original artwork — unique piece",
    prod_tirage: "Fine-art print — limited edition",
    prod_affiche: "Poster",
    edition_of: "edition of",
    stock_left: "still available",
    last_one: "last one",
    sold_out: "Sold out",
    cert_included: "Certificate of authenticity included",
    qty: "Quantity",
    delivery_mode: "Delivery",
    delivery_ship: "Worldwide insured shipping",
    delivery_pickup: "Pickup in Tahiti (studio / opening)",
    payment_method: "Secure payment",
    pay_card: "Credit card",
    pay_transfer: "Bank transfer",
    pay_paypal: "PayPal",
    order_success: "Thank you! Your order has been recorded.",
    merci_title: "Māuruuru!",
    merci_lede: "Your order is recorded. Pascal will write to you personally within 48 h to confirm payment and arrange delivery of your artwork.",
    merci_back: "Back to the gallery",
    news_t: "Letters from the studio",
    news_p: "New works, openings, collections: receive Pascal's announcements, only a few times a year.",
    news_ph: "Your email",
    news_btn: "Subscribe",
    news_ok: "Welcome to the studio letters!",
    news_err: "Invalid or already subscribed address.",
    sold: "Sold",
    new: "New",
    available: "Available",
    add_to_cart: "Acquire this work",
    in_cart: "In your cart",
    view_work: "View work",
    spec_year: "Year",
    spec_technique: "Medium",
    spec_dimensions: "Dimensions",
    spec_collection: "Collection",
    spec_availability: "Availability",
    assur1: "Unique original work, signed, with certificate of authenticity.",
    assur2: "Insured worldwide delivery with professional art packaging.",
    assur3: "Secure payment or bank transfer — Pascal personally confirms every step.",
    related_title: "You may also love",
    back_gallery: "← Back to gallery",
    cart_title: "Your cart",
    cart_lede: "Each work being unique, it is reserved for you as soon as you send your acquisition request.",
    cart_empty_t: "Your cart is empty",
    cart_empty_p: "Pascal's canvases are waiting to meet your gaze.",
    order_title: "Acquisition request",
    order_sub: "Subtotal",
    order_ship: "Shipping",
    order_ship_val: "Personal quote",
    order_total: "Artworks total",
    f_name: "Full name",
    f_email: "Email",
    f_country: "Delivery country",
    f_message: "Message (optional)",
    f_message_ph: "A word for Pascal, a question about the work…",
    order_btn: "Send my request",
    order_note: "Sending your request opens your email app with the summary ready to go. Pascal replies personally within 48 h with secure payment and delivery details.",
    remove: "Remove",
    contact_eyebrow: "Contact",
    contact_title: "Write to Pascal",
    contact_lede: "A question about a work, a special commission, an exhibition project? Pascal reads and answers every message personally, from his studio in Tahiti.",
    f_subject: "Subject",
    f_subject_ph: "Question about a work, custom commission…",
    contact_btn: "Send message",
    studio_t: "The studio",
    studio_p: "Tahiti — French Polynesia",
    followup_t: "Reply",
    followup_p: "Personal, within 48 h",
    ship_t: "Shipping",
    ship_p: "Worldwide, insured",
    footer_tag: "Online gallery of painter Pascal Sun. Polynesian scenes of life — black, white, and a touch of emotion.",
    footer_nav: "Navigation",
    footer_info: "Information",
    footer_ship: "Insured worldwide delivery",
    footer_cert: "Certificate of authenticity",
    footer_secure: "Secure payment",
    footer_rights: "© 2026 Pascal Sun — All rights reserved.",
    footer_made: "Tahiti, French Polynesia",
    toast_added: "added to your cart",
    toast_removed: "removed from cart",
    order_mail_subject: "Acquisition request — Pascal Sun Gallery",
    works_count: "works",
    work_count: "work"
  }
};

/* Adresse de contact de l'artiste — à remplacer par la vraie adresse. */
const ARTIST_EMAIL = "contact@pascal-sun.com";
