/* =========================================================================
   Données de la galerie Pascal Sun
   ➜ Pour publier une nouvelle œuvre : ajouter un objet dans ARTWORKS
     et déposer la photo dans /img (remplacer les visuels SVG d'attente
     par les photos réelles des toiles, même nom de fichier ou nouveau).
   ➜ prixEUR : prix de base en euros (conversion auto XPF / USD).
   ➜ vendu : true pour afficher « Œuvre vendue ».
   ========================================================================= */

var ARTWORKS = [
  {
    id: "retour-du-pecheur",
    titre: "Le retour du pêcheur",
    collection: "ocean",
    annee: 2025,
    technique_fr: "Acrylique et encre sur toile",
    technique_en: "Acrylic and ink on canvas",
    dimensions: "80 × 60 cm",
    orientation: "landscape",
    prixEUR: 1450,
    vendu: false,
    nouveaute: true,
    image: "img/retour-du-pecheur.svg",
    desc_fr: "Au petit matin, une pirogue rentre seule vers le rivage. Le soleil, unique touche de corail, suffit à raconter la promesse du jour. Tout le reste est silence.",
    desc_en: "At dawn, a lone outrigger canoe returns to shore. The sun, a single touch of coral, is enough to tell the promise of the day. Everything else is silence."
  },
  {
    id: "vahine-a-la-fleur",
    titre: "Vahine à la fleur",
    collection: "vahine",
    annee: 2025,
    technique_fr: "Encre de Chine et acrylique sur toile",
    technique_en: "India ink and acrylic on canvas",
    dimensions: "60 × 80 cm",
    orientation: "portrait",
    prixEUR: 1650,
    vendu: false,
    nouveaute: true,
    image: "img/vahine-a-la-fleur.svg",
    desc_fr: "Un profil suggéré en quelques traits, un regard baissé, et l'hibiscus posé sur l'oreille droite — cœur libre. La couleur n'est pas un ornement : elle est l'émotion même.",
    desc_en: "A profile suggested in a few strokes, lowered eyes, and the hibiscus worn on the right ear — a free heart. Colour here is not ornament: it is the emotion itself."
  },
  {
    id: "le-vieux-truck",
    titre: "Le vieux truck",
    collection: "autrefois",
    annee: 2024,
    technique_fr: "Acrylique sur toile de lin",
    technique_en: "Acrylic on linen canvas",
    dimensions: "100 × 73 cm",
    orientation: "landscape",
    prixEUR: 1900,
    vendu: false,
    nouveaute: false,
    image: "img/le-vieux-truck.svg",
    desc_fr: "Le truck d'autrefois, celui qui reliait les villages en chantant sur la route de ceinture. Une cabine turquoise, des souvenirs plein la benne.",
    desc_en: "The old island truck, the one that linked the villages singing along the coastal road. A turquoise cab, and a bed full of memories."
  },
  {
    id: "pirogue-au-lagon",
    titre: "Pirogue au lagon",
    collection: "ocean",
    annee: 2024,
    technique_fr: "Encre et acrylique sur toile",
    technique_en: "Ink and acrylic on canvas",
    dimensions: "50 × 70 cm",
    orientation: "portrait",
    prixEUR: 1150,
    vendu: false,
    nouveaute: false,
    image: "img/pirogue-au-lagon.svg",
    desc_fr: "Un va'a minuscule sous un ciel immense. L'espace laissé libre n'est pas vide : c'est lui qui laisse respirer le regard, et l'imagination compléter l'histoire.",
    desc_en: "A tiny va'a beneath an immense sky. The open space is not emptiness: it lets the gaze breathe, and the imagination complete the story."
  },
  {
    id: "marche-de-papeete",
    titre: "Le marché de Papeete",
    collection: "village",
    annee: 2025,
    technique_fr: "Acrylique sur toile",
    technique_en: "Acrylic on canvas",
    dimensions: "80 × 80 cm",
    orientation: "portrait",
    prixEUR: 1750,
    vendu: true,
    nouveaute: false,
    image: "img/marche-de-papeete.svg",
    desc_fr: "Sous les parasols du marché, les gestes simples d'un matin ordinaire. Une tranche de pastèque, éclat de corail au milieu de l'encre, guide le regard vers l'essentiel.",
    desc_en: "Beneath the market parasols, the simple gestures of an ordinary morning. A slice of watermelon, a burst of coral amid the ink, draws the eye to what matters."
  },
  {
    id: "enfant-au-cerf-volant",
    titre: "L'enfant au cerf-volant",
    collection: "village",
    annee: 2024,
    technique_fr: "Encre de Chine et acrylique sur toile",
    technique_en: "India ink and acrylic on canvas",
    dimensions: "60 × 92 cm",
    orientation: "portrait",
    prixEUR: 1350,
    vendu: false,
    nouveaute: false,
    image: "img/enfant-au-cerf-volant.svg",
    desc_fr: "Sur la plage, un enfant tient le ciel au bout d'un fil. Le cerf-volant jaune soleil dit la liberté mieux que n'importe quel discours.",
    desc_en: "On the beach, a child holds the sky at the end of a string. The sun-yellow kite speaks of freedom better than any words could."
  },
  {
    id: "la-vague",
    titre: "La vague",
    collection: "ocean",
    annee: 2025,
    technique_fr: "Encre et acrylique sur toile",
    technique_en: "Ink and acrylic on canvas",
    dimensions: "116 × 73 cm",
    orientation: "landscape",
    prixEUR: 2200,
    vendu: false,
    nouveaute: true,
    image: "img/la-vague.svg",
    desc_fr: "Un seul geste, un seul souffle. La houle de Teahupo'o réduite à sa ligne essentielle, avec une crête lagon pour seule couleur.",
    desc_en: "A single gesture, a single breath. The Teahupo'o swell reduced to its essential line, with a lagoon-blue crest as its only colour."
  },
  {
    id: "tane-et-le-filet",
    titre: "Tāne et le filet",
    collection: "autrefois",
    annee: 2023,
    technique_fr: "Acrylique sur toile",
    technique_en: "Acrylic on canvas",
    dimensions: "73 × 100 cm",
    orientation: "landscape",
    prixEUR: 1800,
    vendu: true,
    nouveaute: false,
    image: "img/tane-et-le-filet.svg",
    desc_fr: "Le lancer du filet, geste transmis de père en fils depuis des générations. Le soleil se lève exactement là où le filet retombe : ce n'est pas un hasard.",
    desc_en: "The casting of the net, a gesture handed down from father to son for generations. The sun rises exactly where the net falls: that is no coincidence."
  },
  {
    id: "la-case-au-bord-de-l-eau",
    titre: "La case au bord de l'eau",
    collection: "village",
    annee: 2024,
    technique_fr: "Acrylique sur toile de lin",
    technique_en: "Acrylic on linen canvas",
    dimensions: "70 × 50 cm",
    orientation: "landscape",
    prixEUR: 1250,
    vendu: false,
    nouveaute: false,
    image: "img/la-case-au-bord-de-l-eau.svg",
    desc_fr: "Une case, un cocotier, un reflet. Le toit de pandanus, ocre et chaud, est la seule couleur dont ce paysage a besoin pour être habité.",
    desc_en: "A hut, a coconut tree, a reflection. The warm ochre pandanus roof is the only colour this landscape needs to feel inhabited."
  },
  {
    id: "raie-manta",
    titre: "Raie manta",
    collection: "ocean",
    annee: 2025,
    technique_fr: "Encre de Chine sur toile",
    technique_en: "India ink on canvas",
    dimensions: "80 × 116 cm",
    orientation: "portrait",
    prixEUR: 2400,
    vendu: false,
    nouveaute: true,
    image: "img/raie-manta.svg",
    desc_fr: "Elle glisse dans le bleu sans un bruit, immense et paisible. Un petit poisson corail l'accompagne : le grand protège toujours le petit.",
    desc_en: "She glides through the blue without a sound, immense and serene. A small coral fish travels with her: the great always shelters the small."
  },
  {
    id: "ukulele-au-crepuscule",
    titre: "Ukulélé au crépuscule",
    collection: "village",
    annee: 2023,
    technique_fr: "Acrylique et encre sur toile",
    technique_en: "Acrylic and ink on canvas",
    dimensions: "54 × 73 cm",
    orientation: "portrait",
    prixEUR: 1100,
    vendu: false,
    nouveaute: false,
    image: "img/ukulele-au-crepuscule.svg",
    desc_fr: "Assis face au couchant, un homme joue pour personne et pour tout le monde. La musique ne s'entend pas ; elle se devine dans le soleil qui s'attarde.",
    desc_en: "Sitting before the sunset, a man plays for no one and for everyone. You cannot hear the music; you sense it in the lingering sun."
  },
  {
    id: "les-deux-cocotiers",
    titre: "Les deux cocotiers",
    collection: "autrefois",
    annee: 2024,
    technique_fr: "Encre et acrylique sur toile",
    technique_en: "Ink and acrylic on canvas",
    dimensions: "60 × 120 cm",
    orientation: "portrait",
    prixEUR: 1550,
    vendu: false,
    nouveaute: false,
    image: "img/les-deux-cocotiers.svg",
    desc_fr: "Deux cocotiers penchés l'un vers l'autre, comme deux vieux amis au bord du chemin. Ils se racontent le vent depuis cinquante ans.",
    desc_en: "Two coconut palms leaning toward each other, like two old friends by the roadside. They have been telling each other about the wind for fifty years."
  }
];

/* --------------------------------------------------------- vernissages -- */
/* Feuille de route des expositions — modifiable dans l'espace admin.
   date au format AAAA-MM-JJ ; les dates futures s'affichent en « À venir ». */

var EVENTS = [
  {
    id: "vernissage-lagon",
    titre: "Vernissage — Collection Lagon",
    lieu: "Galerie d'art, front de mer",
    ville: "Papeete, Tahiti",
    date: "2026-09-18",
    heure: "18h00",
    desc_fr: "Présentation des nouvelles toiles de la collection Océan & pirogues, en présence de l'artiste. Cocktail au coucher du soleil.",
    desc_en: "Unveiling of the new Ocean & canoes collection, in the artist's presence. Sunset cocktail."
  },
  {
    id: "expo-fenua",
    titre: "Exposition collective — Artistes du Fenua",
    lieu: "Salle d'exposition municipale",
    ville: "Punaauia, Tahiti",
    date: "2026-11-06",
    heure: "17h30",
    desc_fr: "Pascal Sun expose aux côtés des peintres et sculpteurs du fenua. Trois toiles inédites.",
    desc_en: "Pascal Sun exhibits alongside painters and sculptors of the fenua. Three new canvases."
  },
  {
    id: "marche-artisans-moorea",
    titre: "Rencontre au marché des artisans",
    lieu: "Marché artisanal",
    ville: "Moorea",
    date: "2026-05-30",
    heure: "09h00",
    desc_fr: "Démonstration de peinture en plein air et rencontres autour des scènes de vie polynésiennes.",
    desc_en: "Open-air painting demonstration and conversations around Polynesian scenes of life."
  }
];

/* ------------------------------------------------------------ devises -- */

const CURRENCIES = {
  EUR: { symbol: "€",   rate: 1,      locale: "fr-FR", position: "after"  },
  USD: { symbol: "$",   rate: 1.09,   locale: "en-US", position: "before" },
  XPF: { symbol: "F",   rate: 119.33, locale: "fr-FR", position: "after"  }
};

/* --------------------------------------------------------- collections -- */

const COLLECTIONS = {
  ocean:     { fr: "Océan & pirogues",   en: "Ocean & canoes" },
  vahine:    { fr: "Vahine",             en: "Vahine" },
  village:   { fr: "Vie de village",     en: "Village life" },
  autrefois: { fr: "Scènes d'autrefois", en: "Scenes of yesteryear" }
};

/* ---------------------------------------------------------------- i18n -- */

var I18N = {
  fr: {
    nav_home: "Accueil",
    nav_gallery: "Galerie",
    nav_artist: "L'artiste",
    nav_contact: "Contact",
    nav_cart: "Panier",
    hero_eyebrow: "Galerie d'art — Tahiti, Polynésie française",
    hero_title: "Peindre le <em>silence</em> de la Polynésie",
    hero_lede: "Scènes de vie polynésiennes en noir et blanc, où une seule touche de couleur guide le regard vers l'essentiel. Œuvres originales, expédiées dans le monde entier.",
    hero_cta: "Découvrir la galerie",
    hero_cta2: "Rencontrer l'artiste",
    featured_eyebrow: "Sélection",
    featured_title: "Œuvres récentes",
    see_all: "Toute la galerie",
    quote: "« Je ne peins pas pour remplir une toile. Je peins pour laisser <span class='hl'>respirer une émotion</span>. »",
    quote_cite: "Pascal Sun",
    promise_eyebrow: "La promesse",
    promise_title: "Une fenêtre ouverte sur un monde apaisé",
    promise_lede: "Chaque tableau est une œuvre originale, unique, signée. Elle est pensée pour apporter de la sérénité, du sourire et du bien-être — chez vous, où que vous soyez dans le monde.",
    value1_t: "Originaux signés",
    value1_p: "Chaque œuvre est une pièce unique, signée de la main de Pascal Sun et accompagnée de son certificat d'authenticité.",
    value2_t: "Livraison mondiale",
    value2_p: "Emballage d'art professionnel et expédition assurée depuis Tahiti vers le monde entier, suivi de bout en bout.",
    value3_t: "Un lien direct",
    value3_p: "Vous achetez directement auprès de l'artiste, sans intermédiaire. Chaque acquisition commence par une conversation.",
    gallery_eyebrow: "Catalogue",
    gallery_title: "La galerie",
    gallery_lede: "Œuvres originales disponibles à l'acquisition. Cliquez sur une toile pour la découvrir en grand, lire son histoire et l'acquérir.",
    filter_all: "Toutes",
    artist_eyebrow: "L'univers",
    artist_title: "L'art de Pascal Sun est une invitation à ralentir",
    atelier_video_t: "L'atelier en mouvement",
    atelier_video_p: "Quelques minutes dans l'atelier de Pascal, à Tahiti : le geste, le silence, la toile qui prend vie.",
    nav_expos: "Vernissages",
    expos_eyebrow: "Feuille de route",
    expos_title: "Vernissages & expositions",
    expos_lede: "Rencontrer les toiles en vrai, échanger avec Pascal, partager un moment autour de l'art du fenua : voici les prochains rendez-vous de la galerie.",
    expos_upcoming: "À venir",
    expos_past: "Déjà passés",
    expos_rsvp: "Je serai là",
    expos_rsvp_subject: "Présence au vernissage",
    expos_empty: "Les prochaines dates seront annoncées ici très bientôt.",
    sold: "Œuvre vendue",
    new: "Nouveauté",
    available: "Disponible",
    add_to_cart: "Acquérir cette œuvre",
    in_cart: "Dans votre panier",
    view_work: "Voir l'œuvre",
    spec_year: "Année",
    spec_technique: "Technique",
    spec_dimensions: "Dimensions",
    spec_collection: "Collection",
    spec_availability: "Disponibilité",
    assur1: "Œuvre originale unique, signée, avec certificat d'authenticité.",
    assur2: "Livraison assurée dans le monde entier, emballage d'art professionnel.",
    assur3: "Paiement sécurisé ou virement bancaire — Pascal vous confirme chaque étape personnellement.",
    related_title: "Vous aimerez aussi",
    back_gallery: "← Retour à la galerie",
    cart_title: "Votre panier",
    cart_lede: "Chaque œuvre étant unique, elle est réservée pour vous dès votre demande d'acquisition.",
    cart_empty_t: "Votre panier est vide",
    cart_empty_p: "Les toiles de Pascal n'attendent que votre regard.",
    order_title: "Demande d'acquisition",
    order_sub: "Sous-total",
    order_ship: "Livraison",
    order_ship_val: "Devis personnalisé",
    order_total: "Total œuvres",
    f_name: "Nom complet",
    f_email: "Email",
    f_country: "Pays de livraison",
    f_message: "Message (optionnel)",
    f_message_ph: "Un mot pour Pascal, une question sur l'œuvre…",
    order_btn: "Envoyer ma demande",
    order_note: "En envoyant votre demande, votre messagerie s'ouvre avec le récapitulatif prêt à partir. Pascal vous répond personnellement sous 48 h avec les modalités de paiement sécurisé et de livraison.",
    remove: "Retirer",
    contact_eyebrow: "Contact",
    contact_title: "Écrire à Pascal",
    contact_lede: "Une question sur une œuvre, une commande spéciale, un projet d'exposition ? Pascal lit et répond personnellement à chaque message, depuis son atelier à Tahiti.",
    f_subject: "Sujet",
    f_subject_ph: "Question sur une œuvre, commande personnalisée…",
    contact_btn: "Envoyer le message",
    studio_t: "L'atelier",
    studio_p: "Tahiti — Polynésie française",
    followup_t: "Réponse",
    followup_p: "Personnelle, sous 48 h",
    ship_t: "Expéditions",
    ship_p: "Monde entier, assurées",
    footer_tag: "Galerie en ligne de l'artiste peintre Pascal Sun. Scènes de vie polynésiennes — noir, blanc, et une touche d'émotion.",
    footer_nav: "Navigation",
    footer_info: "Informations",
    footer_ship: "Livraison mondiale assurée",
    footer_cert: "Certificat d'authenticité",
    footer_secure: "Paiement sécurisé",
    footer_rights: "© 2026 Pascal Sun — Tous droits réservés.",
    footer_made: "Tahiti, Polynésie française",
    toast_added: "ajoutée à votre panier",
    toast_removed: "retirée du panier",
    order_mail_subject: "Demande d'acquisition — Galerie Pascal Sun",
    works_count: "œuvres",
    work_count: "œuvre"
  },
  en: {
    nav_home: "Home",
    nav_gallery: "Gallery",
    nav_artist: "The artist",
    nav_contact: "Contact",
    nav_cart: "Cart",
    hero_eyebrow: "Art gallery — Tahiti, French Polynesia",
    hero_title: "Painting the <em>silence</em> of Polynesia",
    hero_lede: "Polynesian scenes of life in black and white, where a single touch of colour draws the eye to what matters. Original works, shipped worldwide.",
    hero_cta: "Explore the gallery",
    hero_cta2: "Meet the artist",
    featured_eyebrow: "Selection",
    featured_title: "Recent works",
    see_all: "Full gallery",
    quote: "“I don't paint to fill a canvas. I paint to let an <span class='hl'>emotion breathe</span>.”",
    quote_cite: "Pascal Sun",
    promise_eyebrow: "The promise",
    promise_title: "A window onto a world at peace",
    promise_lede: "Every painting is an original, one-of-a-kind, signed work. Each is meant to bring serenity, smiles and well-being — to your home, wherever you are in the world.",
    value1_t: "Signed originals",
    value1_p: "Each work is a unique piece, signed by Pascal Sun's hand and accompanied by its certificate of authenticity.",
    value2_t: "Worldwide shipping",
    value2_p: "Professional art packaging and insured shipping from Tahiti to anywhere in the world, tracked door to door.",
    value3_t: "A direct bond",
    value3_p: "You buy directly from the artist, with no intermediary. Every acquisition begins with a conversation.",
    gallery_eyebrow: "Catalogue",
    gallery_title: "The gallery",
    gallery_lede: "Original works available for acquisition. Click a canvas to see it up close, read its story and make it yours.",
    filter_all: "All",
    artist_eyebrow: "The universe",
    artist_title: "Pascal Sun's art is an invitation to slow down",
    atelier_video_t: "The studio in motion",
    atelier_video_p: "A few minutes inside Pascal's studio in Tahiti: the gesture, the silence, the canvas coming to life.",
    nav_expos: "Exhibitions",
    expos_eyebrow: "Roadmap",
    expos_title: "Openings & exhibitions",
    expos_lede: "Meet the canvases in person, talk with Pascal, share a moment around the art of the fenua: here are the gallery's upcoming events.",
    expos_upcoming: "Upcoming",
    expos_past: "Past events",
    expos_rsvp: "I'll be there",
    expos_rsvp_subject: "Attending the opening",
    expos_empty: "Upcoming dates will be announced here very soon.",
    sold: "Sold",
    new: "New",
    available: "Available",
    add_to_cart: "Acquire this work",
    in_cart: "In your cart",
    view_work: "View work",
    spec_year: "Year",
    spec_technique: "Medium",
    spec_dimensions: "Dimensions",
    spec_collection: "Collection",
    spec_availability: "Availability",
    assur1: "Unique original work, signed, with certificate of authenticity.",
    assur2: "Insured worldwide delivery with professional art packaging.",
    assur3: "Secure payment or bank transfer — Pascal personally confirms every step.",
    related_title: "You may also love",
    back_gallery: "← Back to gallery",
    cart_title: "Your cart",
    cart_lede: "Each work being unique, it is reserved for you as soon as you send your acquisition request.",
    cart_empty_t: "Your cart is empty",
    cart_empty_p: "Pascal's canvases are waiting to meet your gaze.",
    order_title: "Acquisition request",
    order_sub: "Subtotal",
    order_ship: "Shipping",
    order_ship_val: "Personal quote",
    order_total: "Artworks total",
    f_name: "Full name",
    f_email: "Email",
    f_country: "Delivery country",
    f_message: "Message (optional)",
    f_message_ph: "A word for Pascal, a question about the work…",
    order_btn: "Send my request",
    order_note: "Sending your request opens your email app with the summary ready to go. Pascal replies personally within 48 h with secure payment and delivery details.",
    remove: "Remove",
    contact_eyebrow: "Contact",
    contact_title: "Write to Pascal",
    contact_lede: "A question about a work, a special commission, an exhibition project? Pascal reads and answers every message personally, from his studio in Tahiti.",
    f_subject: "Subject",
    f_subject_ph: "Question about a work, custom commission…",
    contact_btn: "Send message",
    studio_t: "The studio",
    studio_p: "Tahiti — French Polynesia",
    followup_t: "Reply",
    followup_p: "Personal, within 48 h",
    ship_t: "Shipping",
    ship_p: "Worldwide, insured",
    footer_tag: "Online gallery of painter Pascal Sun. Polynesian scenes of life — black, white, and a touch of emotion.",
    footer_nav: "Navigation",
    footer_info: "Information",
    footer_ship: "Insured worldwide delivery",
    footer_cert: "Certificate of authenticity",
    footer_secure: "Secure payment",
    footer_rights: "© 2026 Pascal Sun — All rights reserved.",
    footer_made: "Tahiti, French Polynesia",
    toast_added: "added to your cart",
    toast_removed: "removed from cart",
    order_mail_subject: "Acquisition request — Pascal Sun Gallery",
    works_count: "works",
    work_count: "work"
  }
};

/* Adresse de contact de l'artiste — à remplacer par la vraie adresse. */
const ARTIST_EMAIL = "contact@pascal-sun.com";
